[[window]]
name = "claude"
startup_script = "claude"

[[session]]
name = "notes vault"
path = "~/notes-vault/"
startup_command = "vi ."
windows = [ "claude" ]

# Marlink projects

[[session]]
name = "governance portal"
path = "~/dev/az-governance-dashboard/"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "knowledge base"
path = "~/dev/knowledge-base"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "spo provisioning engine"
path = "~/dev/spo-provisioning-engine/functionapp"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "orbit next gen"
path = "~/dev/orbit-next-gen"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "infra as code"
path = "~/dev/infra-as-code/"
startup_command = "vi ."
windows = [ "claude" ]

# Personal projects

[[session]]
name = "ohayo"
path = "~/dev/ohayo/"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "whohasthekids"
path = "~/dev/whohasthekids/"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "hayabusa"
path = "~/dev/hayabusa/"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "homelab"
path = "~/dev/homelab/"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "dotfiles"
path = "~/dotfiles/"
startup_command = "vi ."
windows = [ "claude" ]

[[session]]
name = "nvim config"
path = "~/dotfiles/nvim/.config/nvim"
startup_command = "vi ."

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux/.config/tmux"
startup_command = "vi tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/.config/tmux"

