FROM archlinux:latest
RUN pacman -Syu --noconfirm curl sudo base-devel
RUN useradd -m -s /bin/bash testuser \
    && echo "testuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER testuser
WORKDIR /home/testuser
CMD ["bash", "-c", "bash <(curl -fsSL https://raw.githubusercontent.com/arjenbloemsma/dotfiles/trunk/bootstrap.sh) && exec zsh"]
